from __future__ import annotations

from typing import Protocol, TypedDict

from minimal_harness.memory import Memory, MemoryData, Message, TokenUsage


class SessionSummary(TypedDict):
    session_id: str
    agent_name: str
    user_id: str
    scenario_id: str | None
    title: str | None
    created_at: str
    message_count: int
    status: str  # "running" | "idle", filled by the TUI layer


class Session(Protocol):
    """An identity-enriched Memory.

    Carries user/scenario context and delegates all message operations
    to an underlying Memory instance.  Stores that work with ``Session``
    can expose user- and scenario-level information without relying on
    the ``MemoryData.extra`` dict.
    """

    @property
    def session_id(self) -> str: ...
    @property
    def memory_id(self) -> str: ...
    @property
    def agent_name(self) -> str: ...
    @property
    def user_id(self) -> str: ...
    @property
    def scenario_id(self) -> str | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def created_at(self) -> str: ...
    @property
    def memory(self) -> Memory: ...

    def add_message(self, message: Message) -> None: ...
    def get_all_messages(self) -> list[Message]: ...
    def get_forward_messages(self) -> list[Message]: ...
    def clear_messages(self) -> None: ...
    def set_message_usage(self, usage: TokenUsage) -> None: ...
    def get_message_usage(self) -> TokenUsage: ...
    def dump_memory(self) -> MemoryData: ...
    def load_memory(self, data: MemoryData) -> None: ...
